@baseURL = http://<HOST>:<PORT>/api

###
GET {{baseURL}}/notes

###
GET {{baseURL}}/notes/:id

###
POST {{baseURL}}/notes
Content-Type: application/json

{
    "content": "test"
}

###
PUT {{baseURL}}/notes/:id
Content-Type: application/json

{
    "content": "test",
    "important": true
}

###
DELETE {{baseURL}}/notes/3